name: Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.6"

      - name: Install dependencies
        run: sudo apt install -y llvm make

      - name: Install LLVM toolchain
        run: |
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install clang-18 llvm-18-dev lld-18 libclang-18-dev

      - name: Install lit and filecheck
        run: pip install lit filecheck

      - name: Test
        run: make test
